export type UploadRecord = {
  id: string;
  institutionId: string;
  studentId: string;
  title: string;
  unitCode: string;
  unitName: string;
  paperType: string;
  academicYear: string | null;
  description: string | null;
  fileKey: string;
  fileName: string;
  mimeType: string;
  fileSizeBytes: number;
  fileHash: string;
  modelLabel: string | null;
  modelConfidence: number | null;
  modelMetadataJson: string | null;
  reviewedByModelAt: string | null;
  documentFingerprint: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
};
